info:
  title: Trakz API
  name: ${spring.application.name}
  description: Trakz API
  version: 1.0.0
  contact:
    name: Faouzi Mohamed
    email: me@mfaouzi.com

server:
  port: 8080

spring:
  application:
    name: trakz-server
  datasource:
    url: jdbc:mysql://197.153.114.138:3307/trakz
    username: mfaouzi
    password: 1234@5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show_sql: true
  data:
    web:
      pageable:
        default-page-size: 100
        max-page-size: 250
