# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - poli-trakz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_aa2fe3fe5cde412ab723b9b8880679d5 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_ee9e144a48ab4a969e7818100ce097d4 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_aa2fe3fe5cde412ab723b9b8880679d5 }}/faouzimohamed/trakz:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'poli-trakz'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_87b2422c630e48b9807df796c0855557 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_aa2fe3fe5cde412ab723b9b8880679d5 }}/faouzimohamed/trakz:${{ github.sha }}'