# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - trakz

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_5da628b6740c45e99801066ede089fa4 }}
          password: ${{ secrets.AzureAppService_ContainerPassword_77d8f4cfdaba492a8395bd9b138a3ab5 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          run: ls -l
          push: true
          tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5da628b6740c45e99801066ede089fa4 }}/faouzimohamed/trakz:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'trakz'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_40f9a42811d34a95bab9664154468892 }}
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_5da628b6740c45e99801066ede089fa4 }}/faouzimohamed/trakz:${{ github.sha }}'
